name: Run Python Script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run amalgamation
      working-directory: ./amalgamation/
      run: |
        python amalgamation.py

    - name: Commit and push if changes
      run: |
        git config --global user.email "gerren.14@gmail.com"
        git config --global user.name "CookiedOutMonster"
        git add embedDB.c
        git add embedDB.h
        git diff --staged --quiet || (time git commit -m "Amalgamated source files" && time git push)
