name: Run Tests and Lint

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      changes-detected: ${{ steps.filter.outputs.changes-detected }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changes-detected:
                - 'lib/**'
                - 'src/**'
                - 'test/**'
                - 'platformio.ini'

  lint:
    needs: changes
    if: ${{ needs.changes.outputs.changes-detected == 'true'}}
    name: Run Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subdir: [test, src]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install ClangFormat
        run: sudo apt-get install -y clang-format

      - name: Check clang version
        run: clang-format --version

      - name: Lint
        uses: wearerequired/lint-action@v2
        with:
          clang_format: true
          clang_format_dir: ${{ matrix.subdir }}/
          check_name: lint  ${{ matrix.subdir }}

  build:
    name: Run Tests
    needs: lint
    runs-on: ubuntu-latest
    concurrency:
      group: board-required
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Run tests on the embedded target
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
        run: platformio remote test -r -v -e due
