name: Build Run and Test EmbedDB Distribution Desktop

on:
    push:
        branches: ["update-distribution"]

jobs:
    build_platformIO:
        name: Build and Run EmbedDB Distribution Using PlatformIO
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        
        steps:
            - uses: actions/checkout@v3

            - name: Set environment variable
              run: |
                if [[ "$RUNNER_OS" == "Windows" ]]; then
                    echo "EXPORT_COMMAND=set" >> $GITHUB_ENV
                else
                    echo "EXPORT_COMMAND=export" >> $GITHUB_ENV
                fi
              shell: bash

            - name: Set up Python
              uses: actions/setup-python@v4
            
            - name: Install PlatformIO
              run: |
                python -m pip install --upgrade pip
                python -m pip install platformio

            - name: Run EmbedDB Distribution Example
              run: |
                    pio run -e desktop-dist -t fullclean
                    ${{ env.EXPORT_COMMAND }} PLATFORMIO_BUILD_FLAGS="-DWHICH_PROGRAM=0 -lm"
                    pio run -e desktop-dist -t exec

            - name: Run EmbedDB Distribution Sequential Data Benchmark
              run: |
                    pio run -e desktop-dist -t fullclean
                    ${{ env.EXPORT_COMMAND }} PLATFORMIO_BUILD_FLAGS="-DWHICH_PROGRAM=1 -lm"
                    pio run -e desktop-dist -t exec
            
            - name: Run EmbedDB Distribution Variable Data Benchmark
              run: |
                    pio run -e desktop-dist -t fullclean
                    ${{ env.EXPORT_COMMAND }} PLATFORMIO_BUILD_FLAGS="-DWHICH_PROGRAM=2 -lm"
                    pio run -e desktop-dist -t exec
                
            - name: Run EmbedDB Distribution Query Interface Benchmark
              run: |
                    pio run -e desktop-dist -t fullclean
                    ${{ env.EXPORT_COMMAND }} PLATFORMIO_BUILD_FLAGS="-DWHICH_PROGRAM=3 -lm"
                    pio run -e desktop-dist -t exec
        
    test_platformIO:
        name: Test EmbedDB Distribution using PlatformIO
        needs: build_platformIO
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
            - name: Install PlatformIO
              run: |
                python -m pip install --upgrade pip
                python -m pip install platformio
            - name: Run Tests
              run: pio test -e desktop-dist --junit-output-path "results.xml"

            - name: Publish Unit Test Results
              if: matrix.os == 'ubuntu-latest'
              uses: EnricoMi/publish-unit-test-result-action/composite@v2
              with:
                github_token: ${{ github.token }}
                files: results.xml
                check_name: PlatformIO Ubuntu Distribution Unit Test Results

    build_make:
        name: Build and Run EmbedDB Distribution using Makefile

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v3

            - name: Run EmbedDB Distribution Example
              run: | 
                make clean
                make dist

            - name: Run EmbedDB Distribution Sequential Data Benchmark
              run: |
                make clean
                make dist CFLAGS="-DWHICH_PROGRAM=1"

            - name: Run EmbedDB Distribution Variable Data Benchmark
              run: |
                make clean
                make dist CFLAGS="-DWHICH_PROGRAM=2"

            - name: Run EmbedDB Distribution Query Interface Benchmark
              run: |
                make clean
                make dist CFLAGS="-DWHICH_PROGRAM=3"

    test_make:
        name: Test EmbedDB Distribution using Makefile
        needs: build_make

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
            
        steps:
          - uses: actions/checkout@v3
        
          - name: Get Submodules
            run: git submodule update --init --recursive
        
          - name: Build and Run Distribution Unit Tests
            run: make test-dist
        
          - name: Publish Unit Test Results
            if: matrix.os == 'ubuntu-latest'
            uses: EnricoMi/publish-unit-test-result-action/composite@v2
            with:
              github_token: ${{ github.token }}
              files: ./build/results/*.xml
              check_name: Makefile Ubuntu Distribution Unit Test Results
