name: Run Distribution tests

on:
    push:
      # branches: [ "update-distribution" ]

jobs:
    build:
        name: Run Distibution Tests
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3
          - name: Set up Python
            uses: actions/setup-python@v4
          - name: Install PlatformIO
            run: |
              python -m pip install --upgrade pip
              pip install platformio
          - name: Update Environment Variable
            run: |
              echo "PLATFORMIO_SRC_DIR=distribution/" >> "$GITHUB_ENV"
          - name: Run tests on the embedded target
            env:
              PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
            run:
              platformio remote test -r -v -e due-dist
