name: Run Distribution tests

on:
    push:
      branches: [ "action-testing" ]

jobs:
    build:
        name: Run Distibution Tests
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v3
          - name: Set up Python
            uses: actions/setup-python@v4
          - name: Install PlatformIO
            run: |
              python -m pip install --upgrade pip
              pip install platformio
          - name: Run tests on the embedded target
            env:
              PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
            run: |
              export PLATFORMIO_SRC_DIR=distribution/
              platformio remote test -r -v -e due-dist
